### PR TITLE
Reconnect fix

### PR DESCRIPTION
**Pull request by kn100**
### Description of the pull request
This PR resets the reconnectAttempts int to zero when the state machine transitions to disconnected. This means that the reconnect logic will trigger whenever .connect() is called again.

#### Why is the change necessary?
It's weird that the reconnection logic only works until it's exhausted, and then never again.

### CODE REVIEW

**Comment by kn100** [comment]
Fixes #199

**Comment by annzenkina** [comment]
does this mean there will not be any reconnect attempts anymore after this fix?

**Comment by kn100** [comment]
No, this just correctly resets the reconnection counter so that the reconnection logic works again a second time.

Before, if the connection failed and six reconnection attempts were exceeded, and the user then decided to call connect again, it would retry once, and then fail.

**Comment by WillSewell** [comment]
I added a test that fails at

https://github.com/pusher/pusher-websocket-java/blob/b32079ed6120ad18dcd0fe7f602227d780fabb68/src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java#L402

Without the fix in this PR.

**Pull request merged**
