### PR TITLE
Synchronize queueOnEventThread

### LINKED ISSUE #107: RejectedExecutionException
This started appearing on crash logs after updating to the last version. 

```

Fatal Exception: java.util.concurrent.RejectedExecutionException: Task com.pusher.client.util.Factory$1@345609e9 rejected from java.util.concurrent.ThreadPoolExecutor@12dd666e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 10]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1334)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:583)
       at com.pusher.client.util.Factory.queueOnEventThread(Factory.java:101)
       at com.pusher.client.connection.websocket.WebSocketConnection.connect(WebSocketConnection.java:65)
       at com.pusher.client.Pusher.connect(Pusher.java:175)
       at com.forplay.app.PusherService.startPusher(PusherService.java:171)
       at com.forplay.app.PusherService.attemptToReconnect(PusherService.java:221)
       at com.forplay.app.PusherService.access$500(PusherService.java:46)
       at com.forplay.app.PusherService$2.run(PusherService.java:203)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

### PR DESCRIPTION
**Pull request by jpatel531**
Fixes #107

### CODE REVIEW

**Comment by mdpye** [comment]
This doesn't quite hit the mark. The problem is at the point of use - we still give out references to an `eventQueue` which people can then call methods on later. This tries to ensure we never return an `eventQueue` which has already had `shutdown()` called on it, but it does not ensure that we don't return such an event queue and then call `shutdown()` on it before the caller tries to queue a job.

We need to encapsulate the `eventQueue` reference entirely, so that both the lazy creation and the queuing of items are both guarded by the same lock. Something like

```java
private final Object eventQueueGuard = new Object();
private Executor eventQueue;

public void addJobToEventQueue(Runnable job) {
    synchronized (eventQueueGuard) {
        if (eventQueue == null) {
            eventQueue = new ExecutorServiceBlah();
        }
        eventQueue.execute(job);
    }
}

public void shutdownThreads() {
    synchronized (eventQueueGuard) {
        eventQueue.shutdown();
        eventQueue = null;
    }
}
```

Notice that we still hold the same lock while we put the job on the queue, so we can't shut it down before that happens.

**Comment by mdpye** [comment]
Looking at the latest revision of the code, `getEventQueue()` is no longer public, but the same thing is happening within the class.

`queueOnEventThread()` needs to be synchronized (all synchronized methods in a class share the same lock).

**Comment by mdpye** [comment]
And as `getEventQueue()` is now private with only one call-site, we might as well just in-line it.

**Comment by jpatel531** [comment]
^ @mdpye - is this alright?

**Comment by jpatel531** [comment]
woops, failing teast

**Comment by mdpye** [comment]
LGTM

**Pull request merged**
