### PR TITLE
Fix 115

### PR DESCRIPTION
**Pull request by realtybaron**
I attempted to create a unit test but was unable to reproduce exception under test conditions

### CODE REVIEW

**Comment by jpatel531** [comment]
@realtybaron - would it be possible to revert the whitespace + formatting changes? i _believe_ the main change is fine, but pinging @mdpye for a second opinion

**Comment by realtybaron** [comment]
@jpatel531 it was a bit sloppy, but i *was* able to revert the whitespace + formatting changes

**Comment by mochawich** [comment]
will this be merged soon?
@jpatel531 

Thanks

**Comment by mdpye** [comment]
+1

**Comment by jpatel531** [comment]
Released as v1.2.1

**Pull request merged**
