### PR TITLE
Fix concurrent modification

### LINKED ISSUE #69: java.util.ConcurrentModificationException Crash
Hi,
We're seeing this issue in Crashlytics on some occasions. Of course we can't really reproduce it locally as this is a concurrency issue:
Any idea what's going on?
```
java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$KeyIterator.next(HashMap.java:833)
       at java.util.AbstractCollection.addAll(AbstractCollection.java:76)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:135)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$400(WebSocketConnection.java:26)
       at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:63)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

Thanks!

### PR DESCRIPTION
**Pull request by trevorrjohn**
I wasn't exactly sure how to test this with mockito. Not sure if you can test it. I also just kind of took a stab at a solution, I have not actually ran installed this code and seen it fix the issue so it would be nice if someone could take a look and make sure I am actually solving the problem.

Another potential solution would be to use [`ConcurrentHashMap`](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html), I don't have any real opinions here, but maybe that would be a simpler fix for the time being.

[Fixes #69]

### CODE REVIEW

**Comment by trevorrjohn** [comment]
@zimbatm any thoughts on this.

**Comment by leggetter** [comment]
It's possible that @jpatel531 will have time to look at the library over the next week or so. In doing so he may be able to take a look at this issue.

**Comment by trevorrjohn** [comment]
OK great. Thanks for the update.

**Comment by trevorrjohn** [comment]
@jpatel531 did you ever get some time on this?

**Comment by jpatel531** [comment]
hey there @trevorrjohn  - i'm still planning to have a look at this. any idea on how i would reproduce this error? your addition looks perfectly logical to me on first glance

**Comment by trevorrjohn** [comment]
Unfortunately I don't have repro steps. We have seen the concurrent map modification exception fairly often in our application, but because the nature of concurrency it has been hard to figure out the exact steps to reproduce.

**Comment by jpatel531** [comment]
Closing this PR as it's being carried onto #79

**Pull request closed without merging**
