### PR TITLE
added a callback for unsubscription of channels

### PR DESCRIPTION
**Pull request by daxfrost**
### Description of the pull request

Added callback for when I unsubscribe from channels.

...

#### Why is the change necessary?

So I can get a callback for when I unsubscribe from channels.

...

----

CC @pusher/mobile

### CODE REVIEW

**Comment by zmarkan** [comment]
You can consider a subscription to be terminated immediately from the client's perspective when you call unsubscribe. 
Why would you need a callback?

**Comment by daxfrost** [comment]
@zmarkan I may be missing something here, but is it possible that a race condition could occur between the point of calling unsubscribe & the unsubscription actually completing?

**Comment by zmarkan** [comment]
There is a potential race condition but the worst case scenario is you receive a message or two that you'd otherwise discard. 
Have you experienced this race condition in your application that caused any problems for you?

**Comment by damogallagher** [comment]
We did not experience this scenario.
Ignoring these messages is no problem if they show

We are currently working on an sdk and we want it to be as lightweight as possible and ensure dependencies are only introduced if they really have to be 
When I noticed this pull request I thought it would be another possibility to decrease the size of our sdk

**Comment by daxfrost** [comment]
Understood, let's close this then.

**Pull request closed without merging**
